window.WONDROUS_CONFIG = {
  SUPABASE_URL: "https://YOUR-PROJECT.supabase.co",
  SUPABASE_PUBLISHABLE_KEY: "YOUR_SUPABASE_PUBLISHABLE_OR_ANON_KEY",
  PAYMENT_PROVIDER: "razorpay",
  RAZORPAY_KEY_ID: "",
  SCHOOL_NAME: "Wondrous Music School"
};